Models/ErrorViewModel.cs
namespace InternShipPipeline.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AanmeldenController.cs
using Microsoft.AspNetCore.Mvc;
using Nancy.Json;
using System.IO;
using System.Net;

namespace InternShipPipeline.Controllers
{
    public class AanmeldenController : Controller
    {
        public static string responseMessage;
        public IActionResult AanMelden()
        {
            return View();
        }

        public ActionResult AanmeldFunctie()
        {
            string n = Request.Form["name"];
            string u = Request.Form["username"];
            string p = Request.Form["password"];
            string i = Request.Form["PID"];
            string e = Request.Form["email"];

            //post request MySQL
            string url = "https://azurefunctioninterships4s.azurewebsites.net/api/AanMelden";
            var httpWebRequest = (HttpWebRequest)WebRequest.Create(url);
            httpWebRequest.ContentType = "application/json";
            httpWebRequest.Method = "POST";

            //post request Cosmos
            /*string cosmosurl = "https://azurefunctioninterships4s.azurewebsites.net/api/AanmeldenCosmos";
            var httpwebRequestCosmos = (HttpWebRequest)WebRequest.Create(cosmosurl);
            httpwebRequestCosmos.ContentType = "application/json";
            httpwebRequestCosmos.Method = "POST";*/


            using (var streamWriter = new StreamWriter(httpWebRequest.GetRequestStream()))
            //using (var streamWriterCosmos = new StreamWriter(httpwebRequestCosmos.GetRequestStream()))
            {
                string json = new JavaScriptSerializer().Serialize(new 
                    { 
                        username = u,
                        name = n,
                        password = p,
                        id = i,
                        email = e
                    });

                streamWriter.Write(json);
                //streamWriterCosmos.Write(json);
            }

            //get response MySQL
            var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();
            var streamReader = new StreamReader(httpResponse.GetResponseStream());
            var result = streamReader.ReadToEnd();

            //get response Cosmos
            /*var httpResponseCosmos = (HttpWebResponse)httpwebRequestCosmos.GetResponse();
            var streamReaderCosmos = new StreamReader(httpResponseCosmos.GetResponseStream());
            var resultCosmos = streamReaderCosmos.ReadToEnd();*/

            responseMessage = "MySQl response;" + result; //"Cosmos DB response" + resultCosmos

            return RedirectToAction("AanMelden", "Home");
        }
    }
}

Controllers/HomeController.cs
using InternShipPipeline.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Data.SqlClient;
using System;
using Microsoft.Data.SqlClient;
using System.Data;

namespace InternShipPipeline.Controllers
{
    public class HomeController : Controller
    {

        private readonly ILogger<HomeController> _logger;
        public static string username;
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }


        public IActionResult Inloggen()
        {
            return View();
        }

        public IActionResult Werkgever()
        {
            return View();
        }
        public IActionResult Werknemer()
        {
            return View();
        }

        public IActionResult AanMelden()
        {
            ViewBag.Message = "Aanmeldpagina";
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Schema;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using MySqlX.XDevAPI;
using Nancy.Json;
using System.Net;
using System.IO;

namespace InternShipPipeline.Controllers
{
    public class LoginController : Controller
    {
        public static string responseMessage;
        public IActionResult Inloggen()
        {
            return View();
        }

        /*[HttpPost]
        public ActionResult Check()
        {
            string line;
            var username = Request.Form["username"];
            var password = Request.Form["password"];

            System.IO.StreamReader file = new System.IO.StreamReader(@"D:\home\site\wwwroot\LoginData.txt");
            while ((line = file.ReadLine()) != null)
            {
                if (line == username + " " + password)
                {
                    HomeController.username = username;
                    return RedirectToAction("Clock", "Home");
                }
            }
            return Content("Username and/or password are incorrect"); //RedirectToAction("Privacy", "Home"); 
        }*/

        public ActionResult LoginFunctie()
        { 
            string u = Request.Form["username"];
            string p = Request.Form["password"];
            HomeController.username = u;

            //post request
            string url = "https://azurefunctioninterships4s.azurewebsites.net/api/Inloggen";
            var httpWebRequest = (HttpWebRequest)WebRequest.Create(url);
            httpWebRequest.ContentType = "application/json";
            httpWebRequest.Method = "POST";

            using (var streamWriter = new StreamWriter(httpWebRequest.GetRequestStream()))
            {
                string json = new JavaScriptSerializer().Serialize(new
                {
                    username = u,
                    password = p
                });

                streamWriter.Write(json);
            }

            //get response
            var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();
            var streamReader = new StreamReader(httpResponse.GetResponseStream());
            var result = streamReader.ReadToEnd();

            //check response - redirect or errormessage

            responseMessage = result;

            return RedirectToAction("Werkgever", "Home");
        }
    }
}

Controllers/WerkgeverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR.Protocol;

namespace InternShipPipeline.Controllers
{
    public class WerkgeverController : Controller
    {
        public static string responseMessage;
        public IActionResult Werkgever()
        {
            return View();
        }

        //functies voor database gegevens opvragen
    }
}

Controllers/WerknemerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace InternShipPipeline.Controllers
{
    public class WerknemerController : Controller
    {
        public IActionResult Werknemer()
        {
            return View();
        }

    }
}

Views/Home/AanMelden.cshtml
@{
    ViewData["Title"] = "AanMelden";
    ViewData["ResponseMessage"] = InternShipPipeline.Controllers.AanmeldenController.responseMessage;
}

<h1>AanMelden</h1>

<h4>PersoneelGegevens</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form action="@Url.Action("AanmeldFunctie", "Aanmelden")" method="post">
            <div class="text-danger"></div>
            <div class="form-group">
                <label for="PersoneelID" class="control-label">ID</label>
                <input type="number" id="PID" name="PID" min="1000" max="9999" required class="form-control" />
            </div>
            <div class="form-group">
                <label for="Naam" class="control-label">Naam</label>
                <input type="text" id="name" name="name" pattern="([A-Za-z]{2,20})+[\s]+([A-Za-z]{2,20}){1,}" title="Voornaam en Achternaam vereist, alleen letters" minlength="5" maxlength="50"  required class="form-control" />
            </div>
            <div class="form-group">
                <label for="Username" class="control-label">Username</label>
                <input type="text" id="username" name="username" minlength="5" maxlength="50" required class="form-control" />
            </div>
            <div class="form-group">
                <label for="Wachtwoord" class="control-label">Wachtwoord</label>
                <input type="password" id="password" name="password" minlength="8" maxlength="50" required class="form-control" />
            </div>
            <div class="form-group">
                <label for="Email" class="control-label">Email</label>
                <input type="email" id="email" name="email" required class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <div class="form-group">
                <label for="response">@ViewData["ResponseMessage"]</label>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    ViewData["ReponseMessage"] = InternShipPipeline.Controllers.LoginController.
}

<html>
<body>

    <div class="text-center">
        <h1 class="display-4">Please login</h1>
        <br><br>

        <form action="@Url.Action("Check", "Login")" method="post">
            <!--Text file?-->
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" minlength="5" maxlength="50" title="Geen geldige username" required class="form-control">
            <br><br>


            <label for="password">Password:</label>
            <input type="password" id="password" name="password" minlength="8" maxlength="50" title="Geen geldig password" required class="form-control">
            <br><br>

            <input type="submit" id="submit" name="submit" value="Log in">
            <label for=response>@ViewData["ResponseMessage"]</label>
        </form>

        <br>
        <p>Login if you want to clock in or clock out.</p>
        <!--Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a> -->

    </div>

</body>
</html>

Views/Home/Inloggen.cshtml
@{
    ViewData["Title"] = "Home Page";
    ViewData["ReponseMessage"] = InternShipPipeline.Controllers.LoginController.responseMessage;
}

<html>
<body>

    <div class="text-center">
        <h1 class="display-4">Please login</h1>
        <br><br>

        <form action="@Url.Action("LoginFunctie", "Login")" method="post">
            <!--Text file?-->
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" minlength="5" maxlength="50" title="Geen geldige username" required class="form-control">
            <br><br>


            <label for="password">Password:</label>
            <input type="password" id="password" name="password" minlength="8" maxlength="50" title="Geen geldig password" required class="form-control">
            <br><br>

            <input type="submit" id="submit" name="submit" value="Log in">
            <label for=response>@ViewData["ResponseMessage"]</label>
        </form>
    </div>

</body>
</html>

Views/Home/Werkgever.cshtml
@{
    ViewData["Username"] = InternShipPipeline.Controllers.HomeController.username;
}

<h1>Welkom, werkgever @ViewData["Username"] </h1>

<html>
<body>

</body>
</html>

Views/Home/Werknemer.cshtml
@{
    ViewData["Username"] = InternShipPipeline.Controllers.HomeController.username;
}

<h1>Welkom, werknemer @ViewData["Username"] </h1>

<html>
<body>

</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InternShipPipeline</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Inloggen">InternShipPipeline</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Inloggen">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AanMelden">Aanmelden</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - InternShipPipeline - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>